services:

  mysql:
    image: mysql:8.0.41
    container_name: moodyclues_mysql_container_local
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodyclues_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3313:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sentiment:
    build:
      context: ./sentiment-service
    container_name: moodyclues-sentiment
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./backend-spring./MoodyClues
    container_name: moodyclues-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moodyclues_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Singapore
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SENTIMENT_SERVICE_URL: http://sentiment:5000
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-reactjs
    container_name: moodyclues-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - sentiment

volumes:
  mysql_data: